// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: api/v1/grpc/storymetadata.proto

package storymetadata_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StorymetadataClient is the client API for Storymetadata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorymetadataClient interface {
	GetMetadata(ctx context.Context, in *GetStoryMetadataRequest, opts ...grpc.CallOption) (*GetStoryMetadataResponse, error)
}

type storymetadataClient struct {
	cc grpc.ClientConnInterface
}

func NewStorymetadataClient(cc grpc.ClientConnInterface) StorymetadataClient {
	return &storymetadataClient{cc}
}

func (c *storymetadataClient) GetMetadata(ctx context.Context, in *GetStoryMetadataRequest, opts ...grpc.CallOption) (*GetStoryMetadataResponse, error) {
	out := new(GetStoryMetadataResponse)
	err := c.cc.Invoke(ctx, "/storymetadata.v1.storymetadata/GetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorymetadataServer is the server API for Storymetadata service.
// All implementations must embed UnimplementedStorymetadataServer
// for forward compatibility
type StorymetadataServer interface {
	GetMetadata(context.Context, *GetStoryMetadataRequest) (*GetStoryMetadataResponse, error)
	mustEmbedUnimplementedStorymetadataServer()
}

// UnimplementedStorymetadataServer must be embedded to have forward compatible implementations.
type UnimplementedStorymetadataServer struct {
}

func (UnimplementedStorymetadataServer) GetMetadata(context.Context, *GetStoryMetadataRequest) (*GetStoryMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedStorymetadataServer) mustEmbedUnimplementedStorymetadataServer() {}

// UnsafeStorymetadataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorymetadataServer will
// result in compilation errors.
type UnsafeStorymetadataServer interface {
	mustEmbedUnimplementedStorymetadataServer()
}

func RegisterStorymetadataServer(s grpc.ServiceRegistrar, srv StorymetadataServer) {
	s.RegisterService(&Storymetadata_ServiceDesc, srv)
}

func _Storymetadata_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoryMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorymetadataServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storymetadata.v1.storymetadata/GetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorymetadataServer).GetMetadata(ctx, req.(*GetStoryMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Storymetadata_ServiceDesc is the grpc.ServiceDesc for Storymetadata service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Storymetadata_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storymetadata.v1.storymetadata",
	HandlerType: (*StorymetadataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _Storymetadata_GetMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/grpc/storymetadata.proto",
}
